#!/sbin/openrc-run

pidfile="/run/ananicy-cpp.pid"
command="/usr/bin/ananicy-cpp"
command_args="start"
command_background=true

start_pre() {
	/usr/sbin/sysctl -e kernel.sched_autogroup_enabled=0
	if [ $? -ne 0 ]
	then
		/sbin/sysctl -e kernel.sched_autogroup_enabled=0
	fi
}

stop_post() {
	/usr/sbin/sysctl -e kernel.sched_autogroup_enabled=1
	if [ $? -ne 0 ]
	then
		/sbin/sysctl -e kernel.sched_autogroup_enabled=1
	fi
}

stop() {
	start-stop-daemon --stop --pidfile "$pidfile"
}
